---
- hosts: kubernetes-master
  gather_facts: no
  tasks:
    - name: Install python3-pip
      apt: 
        name: python3-pip
        update_cache: yes
        state: present

    - name: Install additional python modules for k8s
      pip:
        name: "{{ item }}"
      with_items:
        - kubernetes
        - openshift
    - name: Check if the node is already labeled
      shell: |
        kubectl get nodes k8s-lb --show-labels
      register: k8s_node_label

    - name: Label the lb node with the role used in ds 
      shell: |
        kubectl label node k8s-lb role=lb
      when: k8s_node_label.stdout.find("role=lb") == -1
      
  
    - name: Create ns and service account
      k8s:
        state: present
        src: {{ playbook_dir }}/nginx-ingress/ns-and-sa.yaml

    - name: Create secret
      k8s:
        state: present
        src: {{ playbook_dir }}/nginx-ingress/default-server-secret.yaml

    - name: Create nginx config
      k8s:
        state: present
        src: {{ playbook_dir }}/nginx-ingress/nginx-config.yaml

    - name: Create custom resource definition
      k8s:
        state: present
        src: {{ playbook_dir }}/nginx-ingress/custom-resource-definitions.yaml

    - name: Create RBAC
      k8s:
        state: present
        src: {{ playbook_dir}}/nginx-ingress/rbac.yaml

    - name: Deploy the nginx ingress controller
      k8s:
        state: present
        src: {{ playbook_dir}}/nginx-ingress/ds-nginx-ingress.yaml