apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex2-app
  namespace: default
  labels:
    app: ex2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ex2-app
  template:
    metadata:
      labels:
        app: ex2-app
    spec:
      containers:
        - image: iulianroman/ex2-app
          imagePullPolicy: Always
          name: ex2-app
          env:
            - name: APPPORT
              value: "9000"
            - name: COLNAME
              value: "customcol" 
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: ex2-app-config
                  key: MONGO_URL
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: ex2-app-config
                  key: MONGO_DATABASE
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ex2-app-service
spec:
  ports:
      # service port in cluster
    - port: 9000
      # port to contact inside container
      targetPort: 9000
  selector:
    app: ex2-app
