- name: Copying token to worker nodes
  copy: 
    src: "{{ token_file }}"  
    dest: /tmp/join_token

- name: Joining worker nodes with kubernetes master
  shell: |
    kubeadm reset -f
    echo "$(cat /tmp/join_token | tail -2) --node-name k8s-lb" | bash