- name: Pulling images required for setting up a Kubernetes cluster
  shell: kubeadm config images pull

- name: Resetting kubeadm
  shell: kubeadm reset -f
  register: output

- name: Initializing Kubernetes cluster
  shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{pod_cidr}} --ignore-preflight-errors=NumCPU,FileExisting-nsenter
  register: output

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest={{ playbook_dir }}/roles/k8s-node/files/{{ token_file }}

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest={{ playbook_dir }}/roles/k8s-node-lb/files/{{ token_file }}

- name: Copying required files
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Network Add-on
  command: kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml

- name: Pause for 2 minutes
  pause:
    minutes: 2
